# Stage 1: Builder

FROM node:18-alpine AS builder

# Install elm and required js/ts tooling
WORKDIR /app
COPY package.json package-lock.json ./
RUN nmp install

# Copy source code
COPY . .

# Build project
RUN npm run build


# Stage 2: Static Web Server

FROM nginx:alpine AS production

COPY --from=builder /app/build /usr/share/nginx/html

# expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
