services:
  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    volumes:
      - "./backend:/app"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/usr/src/app"
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: "postgres:17.2-alpine"
    env_file:
      - ".env"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres_data:

